/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderitp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mycode.DBconnect_1;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author N Ξ ✘ U 𝙕
 */
public class delivery1 extends javax.swing.JFrame {
    
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs2=null;
    int i = 0;
    
    
    public void tableload()
    {
        
        try{
        String sql = "select Cid,cName,cAddress,description,iName,vehicleId,driverId,orderId,Quantity, from delivary";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        dtable.setModel(DbUtils.resultSetToTableModel(rs));
        
       
        }catch (Exception e){
       
        }
    }
    


    /**
     * Creates new form delivery1
     */
    public delivery1() {
        initComponents();
        con = DBconnect_1.connect(); 
        
        tableload();
    }
    public ArrayList <user> userlist(){
        ArrayList <user> userlist = new ArrayList <>();
        String names = searchbox.getText();
        
     try{
      String sql = "select * from delivary where cName like \"%"+names+"%\"";
      pst = con.prepareStatement(sql);
      rs = pst.executeQuery();
      user user;
      while(rs.next()){
          user = new user(rs.getInt("cid"),rs.getString("cName"),rs.getString("cAddress"),rs.getString("description"),rs.getString("iName"),rs.getString("vehicleId"),rs.getString("driverId"),rs.getString("orderId"),rs.getString("Quantity"));
          userlist.add(user);
      }
       
    }catch(Exception e){
         e.printStackTrace();
   }
     return userlist;
    }
    
    
   public void displayuser()
  {
      ArrayList<user> list = userlist();
      DefaultTableModel model = (DefaultTableModel) dtable.getModel();
      Object[] row = new Object[9];
      model.setRowCount(0);
      for (int i=0;i<list.size();i++){
          row[0]=list.get(i).getcid();
          row[1]=list.get(i).getname();
          row[2]=list.get(i).getaddress();
          row[3]=list.get(i).getdes();
          row[4]=list.get(i).getiname();
          row[5]=list.get(i).getvid();
          //row[6]=list.get(i).getavid();
          row[6]=list.get(i).getdid();
          row[7]=list.get(i).getdname();
          row[8]=list.get(i).getquantity();
          model.addRow(row);
      }
  } 
    /**o
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        getinfbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Customer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 250, 80, 16);

        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 340, 76, 14);

        jLabel3.setText("Customer Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 390, 88, 14);

        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 490, 53, 14);

        jLabel5.setText("Item name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 440, 51, 14);

        jLabel7.setText("Vehicle ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 590, 47, 14);

        jLabel9.setText("Driver ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 650, 43, 14);

        idtxt.setText(" ");
        getContentPane().add(idtxt);
        idtxt.setBounds(350, 250, 90, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 340, 80, 20);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 390, 78, 20);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 490, 78, 20);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 440, 78, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(210, 590, 78, 20);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(210, 650, 78, 20);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(210, 710, 78, 20);

        jLabel11.setText("Order ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 710, 71, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Delivery Management System");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 130, 316, 66);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 810, 80, 90);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 830, 79, 25);

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn);
        deletebtn.setBounds(480, 830, 75, 25);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Order Search");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(630, 60, 86, 14);

        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox);
        searchbox.setBounds(740, 60, 192, 20);

        dtable.setBackground(new java.awt.Color(255, 153, 102));
        dtable.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus_ID", "Cus_Name", "Cus_Address", "Description", "Item Name", "Vehicle ID", "DriverID", "Order ID", "Quantity"
            }
        ));
        dtable.setSelectionBackground(new java.awt.Color(0, 255, 51));
        jScrollPane1.setViewportView(dtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 120, 800, 320);

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 540, 42, 14);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(210, 540, 78, 20);

        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn);
        searchbtn.setBounds(980, 60, 65, 23);

        getinfbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getinfbtn.setText("GetInfo.");
        getinfbtn.setActionCommand("");
        getinfbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getinfbtnActionPerformed(evt);
            }
        });
        getContentPane().add(getinfbtn);
        getinfbtn.setBounds(460, 250, 90, 30);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1080, 60, 70, 23);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -10, 2810, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cid = idtxt.getText();
        String cname = jTextField2.getText();
        String caddress = jTextField3.getText();
        String description = jTextField4.getText();
        String iname = jTextField5.getText();
        String vid = jTextField7.getText();
        //String avid = jTextField8.getText();
        String did = jTextField9.getText();
        String oid = jTextField10.getText();
        String qty = jTextField6.getText();
        
        
        
        
    try{
        
        String q = "update delivary set cName=\""+cname+"\",cAddress =\""+caddress+"\",description=\""+description+"\",iName=\""+iname+"\",vehicleId=\""+vid+"\",driverId=\""+did+"\",orderId=\""+oid+"\",Quantity=\""+qty+"\" where Cid=\""+cid+"\"";
        pst = con.prepareCall(q);
        i = pst.executeUpdate();
        
        
        if (i !=0){
            JOptionPane.showMessageDialog(null,"data updated");
            
        }
        else{
             JOptionPane.showMessageDialog(null,"data update failed");
        }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    
             displayuser();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        String cid = idtxt.getText();
        
         try{
        
        String q ="delete from delivary where Cid =\""+cid+"\"";
        pst = con.prepareCall(q);
        i = pst.executeUpdate();
        
        
        if (i !=0){
            JOptionPane.showMessageDialog(null,"Order Deleted");
            
        }
        else{
             JOptionPane.showMessageDialog(null,"Order not found");
        }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
         displayuser();
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String cname = jTextField2.getText();
        String caddress = jTextField3.getText();
        String description = jTextField4.getText();
        String iname = jTextField5.getText();
        String vid = jTextField7.getText();
        //String avid = jTextField8.getText();
        String did = jTextField9.getText();
        String oid = jTextField10.getText();
        String qty = jTextField6.getText();
        
        if(cname.equals("")){
            JOptionPane.showMessageDialog(null, "Fill customer name!!");
        }
        
            if(caddress.equals("")){
            JOptionPane.showMessageDialog(null, "Fill Address!!");
            }
            
                if(description.equals("")){
                JOptionPane.showMessageDialog(null, "Fill description!!");
                }
                
                if(iname.equals("")){
                JOptionPane.showMessageDialog(null, "Fill Item name!!");
                }
                
                if(vid.equals("")){
                JOptionPane.showMessageDialog(null, "Fill Vehical ID!!");
                }
                
                if(did.equals("")){
                JOptionPane.showMessageDialog(null, "Fill Driver ID!!");
                }
                
                if(oid.equals("")){
                JOptionPane.showMessageDialog(null, "Fill Order ID!!");
                }
                
                if(qty.equals("")){
                JOptionPane.showMessageDialog(null, "Fill Quantity!!");
                }
        
        else
    try{
        
        String q = "insert into delivary (cName,cAddress,description,iName,vehicleId,driverId,orderId,Quantity) values ('"+cname+"','"+caddress+"','"+description+"','"+iname+"','"+vid+"','"+did+"','"+oid+"','"+qty+"')";
        pst = con.prepareCall(q);
        i = pst.executeUpdate();
        tableload();
        
        
        if (i !=0){
            JOptionPane.showMessageDialog(null,"Order Added");
            
        }
        else{
             JOptionPane.showMessageDialog(null,"Order not Added");
        }
        }
        catch(SQLException e){
            e.printStackTrace();
        
    
        displayuser();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        displayuser();
    }//GEN-LAST:event_searchbtnActionPerformed

    private void getinfbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getinfbtnActionPerformed
        // TODO add your handling code here:
        String cid = idtxt.getText();
        JTextField cname = jTextField2;
        JTextField caddress = jTextField3;
        JTextField description = jTextField4;
        JTextField iname = jTextField5;
        JTextField vid = jTextField7;
        //JTextField avid = jTextField8;
        JTextField did = jTextField9;
        JTextField oid = jTextField10;
        JTextField qty = jTextField6;
        
        
    try{
        
        String q = "select * from delivary where Cid =\""+cid+"\"";
        pst = con.prepareCall(q);
        rs2 = pst.executeQuery();
        rs2.last();
        i= rs2.getRow();
        rs2.beforeFirst();
        while(rs2.next()){
            cname.setText(rs2.getString(1));
            caddress.setText(rs2.getString(2));
            description.setText(rs2.getString(3));
            iname.setText(rs2.getString(4));
            vid.setText(rs2.getString(5));
            //avid.setText(rs2.getString(6));
            did.setText(rs2.getString(7));
            oid.setText(rs2.getString(8));
            qty.setText(rs2.getString(9));
        }
        
        
        if (i <=0){
            JOptionPane.showMessageDialog(null,"Order not found");
            
        }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_getinfbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        searchbox.setText(null);
     
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((Character.isDigit(c))){
        getToolkit().beep();
        evt.consume();
    }//GEN-LAST:event_jTextField2KeyTyped
    }
    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((Character.isDigit(c))){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_jTextField10KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delivery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delivery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delivery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delivery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delivery1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JTable dtable;
    private javax.swing.JButton getinfbtn;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables

   
  
}
