package orderitp;


import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.vipooshan
 */
public class management extends javax.swing.JFrame {

    //private Object txtBillno;

    /**
     * Creates new form management
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public management() {
        initComponents();
        conn=DBconnectio.getConnection();
         currentDate();
        //conn.DBconnection.connect();
        
    }
    String date;
    public void currentDate(){
        
        Date date1 = new Date();
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        date = d.format(date1);
        Date0.setText(date);
        
    }
    
    public static boolean valphone(String in){
        
        return in.charAt(0)=='0'&&in.charAt(1)=='7'&&in.length() == 10;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Sales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Billno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        Rate = new javax.swing.JTextField();
        Cash = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Date0 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        from = new com.toedter.calendar.JDateChooser();
        to = new com.toedter.calendar.JDateChooser();
        jLabel55 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Sales Management System");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sale-icon.png"))); // NOI18N
        jLabel47.setText("jLabel47");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sales");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Sales");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sales Report");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Sales.setBackground(new java.awt.Color(204, 204, 204));
        Sales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Sales.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Billno");
        Sales.add(jLabel6);
        jLabel6.setBounds(12, 13, 50, 22);

        Billno.setBackground(new java.awt.Color(0, 204, 204));
        Billno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillnoActionPerformed(evt);
            }
        });
        Sales.add(Billno);
        Billno.setBounds(119, 13, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Id");
        Sales.add(jLabel7);
        jLabel7.setBounds(12, 48, 20, 22);

        Id.setBackground(new java.awt.Color(0, 204, 204));
        Id.setForeground(new java.awt.Color(204, 0, 0));
        Sales.add(Id);
        Id.setBounds(120, 50, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Name");
        Sales.add(jLabel9);
        jLabel9.setBounds(12, 133, 53, 22);

        Name.setBackground(new java.awt.Color(0, 204, 204));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Sales.add(Name);
        Name.setBounds(120, 130, 150, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Contact");
        Sales.add(jLabel12);
        jLabel12.setBounds(12, 173, 70, 22);

        Contact.setBackground(new java.awt.Color(0, 204, 204));
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContactKeyTyped(evt);
            }
        });
        Sales.add(Contact);
        Contact.setBounds(119, 167, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Qty");
        Sales.add(jLabel13);
        jLabel13.setBounds(12, 215, 31, 22);

        Qty.setBackground(new java.awt.Color(0, 204, 204));
        Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QtyKeyTyped(evt);
            }
        });
        Sales.add(Qty);
        Qty.setBounds(120, 210, 150, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Rate");
        Sales.add(jLabel14);
        jLabel14.setBounds(12, 517, 42, 22);
        Sales.add(jTextField9);
        jTextField9.setBounds(119, 521, 302, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Availabe");
        Sales.add(jLabel15);
        jLabel15.setBounds(12, 578, 76, 22);
        Sales.add(jTextField10);
        jTextField10.setBounds(119, 582, 302, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Total");
        Sales.add(jLabel16);
        jLabel16.setBounds(12, 633, 45, 22);
        Sales.add(jTextField11);
        jTextField11.setBounds(119, 637, 302, 20);

        jButton1.setText("Reset");
        Sales.add(jButton1);
        jButton1.setBounds(37, 663, 61, 23);

        jButton2.setText("Save");
        Sales.add(jButton2);
        jButton2.setBounds(159, 663, 57, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Rate");
        Sales.add(jLabel17);
        jLabel17.setBounds(12, 257, 42, 22);

        cash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cash.setText("Cash");
        Sales.add(cash);
        cash.setBounds(12, 299, 44, 22);

        Rate.setBackground(new java.awt.Color(0, 204, 204));
        Rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RateKeyTyped(evt);
            }
        });
        Sales.add(Rate);
        Rate.setBounds(119, 251, 150, 30);

        Cash.setBackground(new java.awt.Color(0, 204, 204));
        Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CashKeyTyped(evt);
            }
        });
        Sales.add(Cash);
        Cash.setBounds(119, 293, 150, 30);

        Save.setBackground(new java.awt.Color(0, 204, 204));
        Save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Actions-document-save-all-icon.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        Sales.add(Save);
        Save.setBounds(160, 350, 100, 31);

        Reset.setBackground(new java.awt.Color(0, 204, 204));
        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button-Reload-icon.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        Sales.add(Reset);
        Reset.setBounds(160, 410, 110, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Date");
        Sales.add(jLabel8);
        jLabel8.setBounds(12, 93, 43, 22);

        Date0.setBackground(new java.awt.Color(0, 204, 204));
        Sales.add(Date0);
        Date0.setBounds(119, 93, 150, 30);

        jButton9.setBackground(new java.awt.Color(0, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rotate-view-tool-icon.png"))); // NOI18N
        jButton9.setText("View");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Sales.add(jButton9);
        jButton9.setBounds(30, 410, 100, 31);

        jButton11.setBackground(new java.awt.Color(0, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button-Refresh-icon.png"))); // NOI18N
        jButton11.setText("Demo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Sales.add(jButton11);
        jButton11.setBounds(30, 350, 120, 33);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image-43947356-backgrounds-wallpapers-in-hd.jpg"))); // NOI18N
        jLabel65.setText("jLabel65");
        Sales.add(jLabel65);
        jLabel65.setBounds(0, 0, 280, 510);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Sales Receipt");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(60, 10, 120, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Date");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(12, 40, 43, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Id");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(10, 140, 20, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Qty");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(110, 140, 31, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Rate");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(200, 140, 42, 22);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Cash");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(10, 260, 44, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Balance");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(12, 311, 72, 22);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Billno");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(12, 80, 50, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(10, 210, 45, 22);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print-icon.png"))); // NOI18N
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);
        jButton3.setBounds(133, 353, 110, 31);
        jPanel8.add(jLabel11);
        jLabel11.setBounds(153, 40, 0, 0);
        jPanel8.add(jLabel18);
        jLabel18.setBounds(153, 80, 0, 0);
        jPanel8.add(jLabel19);
        jLabel19.setBounds(16, 176, 0, 0);
        jPanel8.add(jLabel25);
        jLabel25.setBounds(68, 176, 0, 0);
        jPanel8.add(jLabel27);
        jLabel27.setBounds(125, 176, 0, 0);
        jPanel8.add(jLabel29);
        jLabel29.setBounds(121, 201, 0, 0);
        jPanel8.add(jLabel41);
        jLabel41.setBounds(121, 250, 0, 0);
        jPanel8.add(jLabel42);
        jLabel42.setBounds(68, 311, 0, 0);
        jPanel8.add(jLabel57);
        jLabel57.setBounds(120, 40, 110, 20);
        jPanel8.add(jLabel58);
        jLabel58.setBounds(120, 80, 80, 20);
        jPanel8.add(jLabel59);
        jLabel59.setBounds(10, 170, 60, 30);
        jPanel8.add(jLabel60);
        jLabel60.setBounds(110, 170, 60, 30);
        jPanel8.add(jLabel61);
        jLabel61.setBounds(200, 170, 70, 30);
        jPanel8.add(jLabel62);
        jLabel62.setBounds(110, 210, 100, 30);
        jPanel8.add(jLabel63);
        jLabel63.setBounds(110, 260, 80, 30);
        jPanel8.add(jLabel64);
        jLabel64.setBounds(110, 314, 90, 20);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image-43947356-backgrounds-wallpapers-in-hd.jpg"))); // NOI18N
        jLabel50.setText("jLabel50");
        jPanel8.add(jLabel50);
        jLabel50.setBounds(0, 0, 280, 510);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("Search SalesId");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(70, 10, 135, 22);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Search ById");
        jPanel9.add(jLabel32);
        jLabel32.setBounds(12, 53, 110, 22);

        search.setBackground(new java.awt.Color(0, 204, 204));
        search.setForeground(new java.awt.Color(255, 0, 0));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel9.add(search);
        search.setBounds(130, 50, 138, 30);

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Zoom-icon.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);
        jButton6.setBounds(140, 110, 115, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Sales Name");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(12, 201, 105, 22);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("SalesId");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(12, 256, 67, 22);

        jButton7.setBackground(new java.awt.Color(0, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button-Close-icon.png"))); // NOI18N
        jButton7.setText("Delete Id");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);
        jButton7.setBounds(110, 320, 150, 30);
        jPanel9.add(jLabel43);
        jLabel43.setBounds(174, 201, 107, 0);
        jPanel9.add(jLabel44);
        jLabel44.setBounds(174, 256, 107, 0);
        jPanel9.add(jLabel48);
        jLabel48.setBounds(150, 200, 120, 20);
        jPanel9.add(jLabel49);
        jLabel49.setBounds(150, 250, 110, 30);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image-43947356-backgrounds-wallpapers-in-hd.jpg"))); // NOI18N
        jLabel45.setText("jLabel45");
        jPanel9.add(jLabel45);
        jLabel45.setBounds(0, 0, 280, 510);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("Profit");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(110, 10, 50, 22);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("From ");
        jPanel10.add(jLabel36);
        jLabel36.setBounds(12, 53, 51, 22);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("To ");
        jPanel10.add(jLabel37);
        jLabel37.setBounds(12, 93, 27, 22);

        jDateChooser4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel10.add(jDateChooser4);
        jDateChooser4.setBounds(81, 53, 140, 30);

        jDateChooser5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel10.add(jDateChooser5);
        jDateChooser5.setBounds(81, 95, 140, 30);

        jButton8.setBackground(new java.awt.Color(0, 204, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rotate-view-tool-icon.png"))); // NOI18N
        jButton8.setText("Show");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8);
        jButton8.setBounds(110, 150, 110, 31);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("Sales Report");
        jPanel10.add(jLabel38);
        jLabel38.setBounds(80, 230, 113, 22);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("From ");
        jPanel10.add(jLabel39);
        jLabel39.setBounds(20, 297, 51, 22);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("To ");
        jPanel10.add(jLabel40);
        jLabel40.setBounds(20, 337, 27, 22);

        jButton10.setBackground(new java.awt.Color(0, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rotate-view-tool-icon.png"))); // NOI18N
        jButton10.setText("Show");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10);
        jButton10.setBounds(130, 390, 103, 31);

        from.setBackground(new java.awt.Color(0, 204, 204));
        jPanel10.add(from);
        from.setBounds(90, 300, 140, 30);

        to.setBackground(new java.awt.Color(0, 204, 204));
        jPanel10.add(to);
        to.setBounds(90, 340, 140, 30);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image-43947356-backgrounds-wallpapers-in-hd.jpg"))); // NOI18N
        jLabel55.setText("jLabel55");
        jPanel10.add(jLabel55);
        jLabel55.setBounds(0, 0, 280, 510);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sales Receipt");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sales, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed

        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ContactActionPerformed

    private void BillnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillnoActionPerformed

    private void ContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactKeyPressed
          
        
        
    }//GEN-LAST:event_ContactKeyPressed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
       
           Billno.setText("");
           Billno.setEnabled(true);
           
           Id.setText("");
           Id.setEnabled(true);
           
           Name.setText("");
           Name.setEnabled(true);
           
           //Balance.setText("");
           //Balance.setEnabled(true);
           
           Contact.setText("");
           Contact.setEnabled(true);
           
           Qty.setText("");
           Qty.setEnabled(true);
           
           
           Rate.setText("");
           Rate.setEnabled(true);
           
           Cash.setText("");
           Cash.setEnabled(true);
           
          // Total.setText("");           
           //Total.setEnabled(true);
           
            
       
    
    
        
    }//GEN-LAST:event_ResetActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
//
//              String From = dateFormat.format(from.getDate());
//              String To = dateFormat.format(to.getDate());
//
//              System.out.println(From);
//              System.out.println(To);
//        
//        
//        try{
//          JasperDesign jd = JRXmlLoader.load("C:\\Users\\A.vipooshan\\SalesReport.jrxml");
//          //SqlDataAdapter sdf = new SqlDataAdapter( "SELECT * FROM sales  where date between '"+dateTimePicker2.Value.ToString() +"'and'" +dateTimePicker3.Value.ToString() + "'");
//          String sql = "SELECT * FROM sales  where date between '"+From + "'and'" +To+ "'";
//          JRDesignQuery newQuery= new JRDesignQuery();
//          newQuery.setText(sql);
//          jd.setQuery(newQuery);
//          JasperReport jr = JasperCompileManager.compileReport(jd);
//          JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
//          JasperViewer.viewReport(jp);
//          
//          
//        
//      } catch (JRException ex) {
//            Logger.getLogger(management.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void QtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyKeyTyped
        Sales_T Numbers = new Sales_T();
        Numbers.numbersonly(evt);
    }//GEN-LAST:event_QtyKeyTyped

    private void RateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RateKeyTyped
        Sales_T Numbers = new Sales_T();
        Numbers.numbersonly(evt);
    }//GEN-LAST:event_RateKeyTyped

    private void CashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashKeyTyped
        Sales_T Numbers = new Sales_T();
        Numbers.numbersonly(evt);
    }//GEN-LAST:event_CashKeyTyped

    private void ContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactKeyTyped
        Sales_T Numbers = new Sales_T();
        Numbers.numbersonly(evt); 
    }//GEN-LAST:event_ContactKeyTyped

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        try{
            int billNo = Integer.parseInt( Billno.getText());
            int id = Integer.parseInt( Id.getText());
        
            //DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
            //String date = dateFormat.format(Date.getDate());
            String dat = date;
            String name = Name.getText();
           // double balance = Double.parseDouble(Balance.getText());
            String contact = Contact.getText();        
            int qty = Integer.parseInt( Qty.getText());
            double rate = Double.parseDouble(Rate.getText());
           double cash = Double.parseDouble( Cash.getText());
            double total =rate*qty;
            double balance = cash-total;
            //String contact = Contact.getText();
                       
            
            
            
            String sql = "Insert into sales(SalesID,billNo,Date,Name,Balance,Contact,Qty,Rate,Cash,Total"
                    + ") values("+id+","+billNo+",'"+dat+"','"+name+"',"+balance+","+contact+","+qty+","+rate+","+cash+","+total+")";
            
            conn = DBconnectio.getConnection();
            pst = conn.prepareStatement(sql);
            
            if(valphone(contact)){
                //JOptionPane.showMessageDialog(null, "Phone Number Valid");
                pst.execute();
                JOptionPane.showMessageDialog(null,"Sale added succesfull");
                
               
           
            }
            else{
                JOptionPane.showMessageDialog(null, "Phone Number InValid");
            }
            
                    
//            Billno.setText("");
//            Id.setText("");
//            Date.setdate();
//            Balance.setText("");
//            Contact.setText("");
//            Qty.setText("");
//            Rate.setText("");
//            Available.setText("");
//            Total.setText("");
            
                    
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
            System.out.println(e);
            e.printStackTrace();
        }
        
      
       
        
    }//GEN-LAST:event_SaveActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     
    try{
            conn = DBconnectio.getConnection();
                   
            String sql ="select SalesId,Name From sales where SalesId = ?";
                 
            pst=conn.prepareStatement(sql);
            pst.setString(1,search.getText());
            rs=pst.executeQuery();
            
          
            
            if(rs.first()){
                String add1 =rs.getString("Name");
                jLabel48.setText(add1);

                
                String add2 =rs.getString("SalesID");
                jLabel49.setText(add2);
            }
            
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
          
        
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
            
        }
           
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql ="delete from sales where SalesID =? ";
            try{
                pst=conn.prepareStatement(sql); 
                pst.setString(1, search.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch( Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch( Exception e){

                }
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
          JasperDesign jd = JRXmlLoader.load("C:\\Users\\Dhanudr\\Desktop\\ITP ALL\\Sales management\\ITP Sales Management\\pro\\Print.jrxml");
          //SqlDataAdapter sdf = new SqlDataAdapter( "SELECT * FROM sales  where date between '"+dateTimePicker2.Value.ToString() +"'and'" +dateTimePicker3.Value.ToString() + "'");
          String sql = "SELECT * FROM sales";
          JRDesignQuery newQuery= new JRDesignQuery();
          newQuery.setText(sql);
          jd.setQuery(newQuery);
          JasperReport jr = JasperCompileManager.compileReport(jd);
          JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
          JasperViewer.viewReport(jp);
                 
           } catch(JRException ex){
            Logger.getLogger(management.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        
        
    }//GEN-LAST:event_NameActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

              String From = dateFormat.format(from.getDate());
              String To = dateFormat.format(to.getDate());

              System.out.println(From);
              System.out.println(To);
        
        try{
          JasperDesign jd = JRXmlLoader.load("C:\\Users\\A.vipooshan\\Desktop\\Sales management\\ITP Sales Management\\pro\\SalesReport.jrxml");
          //SqlDataAdapter sdf = new SqlDataAdapter( "SELECT * FROM sales  where date between '"+dateTimePicker2.Value.ToString() +"'and'" +dateTimePicker3.Value.ToString() + "'");
          String sql = "SELECT * FROM sales  where date between '"+From + "'and'" +To+ "'";
          JRDesignQuery newQuery= new JRDesignQuery();
          newQuery.setText(sql);
          jd.setQuery(newQuery);
          JasperReport jr = JasperCompileManager.compileReport(jd);
          JasperPrint jp = JasperFillManager.fillReport(jr,null,conn);
          JasperViewer.viewReport(jp);
          
          
        
      } catch (JRException ex) {
            Logger.getLogger(management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
           try{
        
        conn = DBconnectio.getConnection();
                   
           
                 String  sql = "select Date,billNo,SalesID,Qty,Rate,Total,Cash,Balance From sales where SalesID = ?";

            pst=conn.prepareStatement(sql);
            pst.setString(1,Id.getText());
            rs=pst.executeQuery();
            
            
            if(rs.first()){
                String add1 =rs.getString("Date");
                jLabel57.setText(add1);

                
                String add2 =rs.getString("billNo");
                jLabel58.setText(add2);
                
                String add3 =rs.getString("SalesID");
                jLabel59.setText(add3);
                
                String add4 =rs.getString("Qty");
                jLabel60.setText(add4);
                
                String add5 =rs.getString("Rate");
                jLabel61.setText(add5);
                
                String add6 =rs.getString("Total");
                jLabel62.setText(add6);
                
                String add7 =rs.getString("Cash");
                jLabel63.setText (add7);
                
                String add8 =rs.getString("Balance");
                jLabel64.setText(add8);
            }
            
              }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Billno.setText("48567");
        Id.setText("1");

        Date0.setText("2018-10-10");

        Name.setText("Samsung");
        Contact.setText("0764692421");
        Qty.setText("3");
        Rate.setText("15000");
        Cash.setText("50000");


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Billno;
    private javax.swing.JTextField Cash;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Date0;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Qty;
    private javax.swing.JTextField Rate;
    private javax.swing.JButton Reset;
    private javax.swing.JPanel Sales;
    private javax.swing.JButton Save;
    private javax.swing.JLabel cash;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField search;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
